--- 
- "Mile run"
- "Walk"
- "Power Walk"
- "Jog"
- "Run"
- "Hike"
- "Sprint"
- "Jump"
- "Swim"
- "Bike"
- "Wrestle"
- "Basketball"
- "Soccer"
- "Football"
- "Futbol"
- "American Football"
- "Elliptical"
- "Stationary Bike"
- "Spinning"
- "Upright Bike"
- "Recumbent Bike"
- "ARC Trainer"
- "AMT"
- "Stairmaster"
- "Stairs"
- "Powermill"
- "Skillmill"
- "Treadmill"
- "Rower"
- "Rowing Machine"
- "Row"
- "Freestyle"
- "Breaststroke"
- "Backstroke"
- "Butterfly"
- "Scuba Diving"
- "Freediving"
- "Snorkeling"
- "Climbing"
- "Bouldering"
- "Alpining"
- "Tumbling"
- "Parkour"
- "Freerunning"
- "Gymnastics"
- "Calisthentics"
- "Plyometrics"
- "Cycling"
- "Indoor Cycling"
- "Barre"
- "Cardio Barre"
- "Dance"
- "Zumba"
- "Bollywood"
