--- 
- "Seated Toe Press"
- "Seated Calf Raise"
- "Rotary Toe Press"
- "Rotary Calf Raise"
- "Angled Toe Press"
- "Angled Calf Raise"
- "Standing Toe Press"
- "Standing Calf Raise"
- "Toe Press"
- "Calf Raise"
- "Toe Press Machine"
- "Calf Raise Machine"
- "Leg Extension"
- "Seated Leg Extension"
- "Leg Extension Machine"
- "Leg Curl"
- "Standing Leg Curl"
- "Leg Curl Machine"
- "Seated Leg Curl"
- "Prone Leg Curl"
- "Leg Press"
- "Leg Press Machine"
- "Angled Leg Press"
- "Vertical Leg Press"
- "Seated Leg Press"
- "Hip Adduction Machine"
- "Hip Abduction Machine"
- "Rotary Hip Machine"
- "Squat"
- "Back Squat"
- "Front Squat"
- "Overhead Squat"
- "Sissy Squat"
- "Low-Bar Squat"
- "High-Bar Squat"
- "Zercher Squat"
- "Assisted Squat"
- "Seated Squat"
- "Deadlift"
- "Sumo Deadlift"
- "Conventional Deadlift"
- "Romanian Deadlift"
- "RDL"
- "Straight Leg Deadlift"
- "Lunge"
- "Reverse Lunge"
- "Crunch"
- "Situp"
- "Reverse Hyperextension"
- "Reverse Hyper"
- "Hyperextension"
- "Back Extension"
- "Straight Leg Raise"
- "Knee Raise"
- "Toe to Bar"
- "Russian Twist"
- "V Up"
- "Toe Touches"
- "Toe Touch"
- "Bench Press"
- "Incline Bench Press"
- "Decline Bench Press"
- "Chest Press"
- "Incline Chest Press"
- "Decline Chest Press"
- "Pec Fly Machine"
- "Fly Machine"
- "Chest Press Machine"
- "Plate Loaded Chest Press"
- "Wide Grip Chest Press"
- "Dumbbell Fly"
- "Incline Fly"
- "Decline Fly"
- "Push Up"
- "Pushup"
- "Close Grip Push Up"
- "Close Grip Pushup"
- "Wide Grip Push Up"
- "Wide Grip Pushup"
- "Wide Pushup"
- "Wide Push Up"
- "Plyometric Push Up"
- "Plyometric Pushup"
- "Incline Push Up"
- "Incline Pushup"
- "Decline Push Up"
- "Decline Pushup"
- "Assisted Push Up"
- "Assisted Pushup"
- "Cable Fly"
- "Pec Deck"
- "Cable Chest Press"
- "Wide Grip Dip"
- "Weighted Dip"
- "Dip"
- "Close Grip Dip"
- "Close Grip Bench"
- "Arm Extension"
- "Arm Extension Machine"
- "Plate Loaded Arm Extension"
- "Seated Dip"
- "Tricep Extension"
- "Triceps Extension"
- "Tricep Kickback"
- "Triceps kickback"
- "Overhead Extension"
- "Skullcrusher"
- "Skullcrushers"
- "Tricep Pressdown"
- "Triceps Pressdown"
- "Horserope Exrtension"
- "Tricep Pushdown"
- "Triceps Pushdown"
- "Cable Pressdown"
- "Cable Pushdown"
- "Military Press"
- "Shoulder Press"
- "Overhead Press"
- "Strict Overhead Press"
- "Strict Press"
- "Jerk"
- "Seated Shoulder Press"
- "Shoulder Press Machine"
- "Front Raise"
- "Anterior Raise"
- "Circus Press"
- "Log Press"
- "Lateral Raise"
- "Reverse Fly"
- "Upright Row"
- "Shrug"
- "Seated Shrug"
- "Plate Loaded Shrug"
- "Dumbbell Shrug"
- "Barbell Shrug"
- "Facepull"
- "Row"
- "Seated Row"
- "Cable Row"
- "Seated Cable Row"
- "Pulldown"
- "Lat Pulldown"
- "Straight Arm Pulldown"
- "Lateral Row"
- "Iso-Lateral Row"
- "Dumbbell Row"
- "Kroc Row"
- "Barbell Row"
- "Pendlay Row"
- "Bent Over Row"
- "Rack Pull"
- "Block Pull"
- "Lat Raise"
- "Close Grip Row"
- "Wide Grip Row"
- "Wide Grip Pulldown"
- "Close Grip Pulldown"
- "Plate Loaded Row"
- "T-Bar Row"
- "T Bar Row"
- "Pullup"
- "Strict Pullup"
- "Kipping Pullup"
- "Butterfly Pullup"
- "Assisted Pullup"
- "Weighted Pullup"
- "Pull-up"
- "Pull Up"
- "Chin Up"
- "Chinup"
- "Chin-up"
- "Inverted Row"
- "Preacher Curl"
- "Zottman Curl"
- "Biceps Curl"
- "Bicep Curl"
- "Curl"
- "Barbell Curl"
- "Reverse Curl"
- "Dumbbell Curl"
- "Hammer Curl"
- "Cable Curl"
- "Standing Curl"
- "Seated Curl"
- "Lying Curl"
- "Incline Curl"
- "Plate Loaded Curl"
- "Arm Curl"
- "Arm Curl Machine"
- "Seated Arm Curl"
- "Forearm Curl"
- "Wrist Curl"
- "Reverse Wrist Curl"

